### ISSUE TITLE
Type errors after migrating to 3.10.0

### ISSUE THREAD

**Issue by kasleet** [anomalyco/sst#5588]
We use `tsc` for type checking in our repo. After upgrading to 3.10.0, this fails:

```
.sst/platform/src/components/aws/astro.ts:387:13 - error TS2416: Property 'buildPlan' in type 'Astro' is not assignable to the same property in base type 'SsrSite'.
  Type '(outputPath: Output<string>) => Output<{ base: any; server: { handler: string; nodejs: { install: string[]; }; streaming: boolean; copyFiles: { from: string; to: string; }[]; } | undefined; assets: { ...; }[]; custom404: string | undefined; }>' is not assignable to type '(outputPath: Output<string>, name: string, args: SsrSiteArgs, { bucket }: { bucket: Bucket; }) => Output<Plan>'.
    Type 'Output<{ base: any; server: { handler: string; nodejs: { install: string[]; }; streaming: boolean; copyFiles: { from: string; to: string; }[]; } | undefined; assets: { from: string; to: string; cached: boolean; versionedSubDir: string; }[]; custom404: string | undefined; }>' is not assignable to type 'Output<Plan>'.
      Property 'assets' is missing in type 'Output<{ base: any; server: { handler: string; nodejs: { install: string[]; }; streaming: boolean; copyFiles: { from: string; to: string; }[]; } | undefined; assets: { from: string; to: string; cached: boolean; versionedSubDir: string; }[]; custom404: string | undefined; }>' but required in type 'LiftedObject<Plan, NonFunctionPropertyNames<Plan>>'.

387   protected buildPlan(outputPath: Output<string>) {
                ~~~~~~~~~

  infrastructure/account/.sst/platform/src/components/aws/ssr-site.ts:88:3
    88   assets: {
         ~~~~~~
    'assets' is declared here.
```

But it has nothing to do with `assets`, but with the `base` prop. In `astro.ts`, the base is defined as `buildMeta.base === "/" ? undefined : buildMeta.base;`, which in my case leads to the type `any`, because the `AstroConfig` import can not be resolved. The imports on top of `astro-sst/src/lib/build-meta.ts` can not be resolved, because the `astro` package is not in my `.sst/platform/node_modules`. Here's the relevant code section:

![Image](https://github.com/user-attachments/assets/4b8a3a2a-1678-4ec0-83d6-ba1d108a1794)

Reverting back to 3.9.44 fixes the issue, as it seems the imports where never used (in my context)

**Comment by jayair** [comment]
Taking a look.

**Comment by kasleet** [comment]
Thanks.

In my opinion, `src/components/aws/astro.ts` should not have a direct dependency to Astro (or indirectly via astro-sst). The class `Astro extends SsrSite` is exported by default and will be loaded each time sst is run, even if Astro is not used. So it should be assumed that the `astro` package is not present. Currently I see only a dependency to the `BuildMetaConfig` type. Maybe as a quick fix the type definition could be copied into `src/components/aws/astro.ts`, though that can be a pain to maintain in the long run.

**Comment by the-simian** [comment]
I can verify i get:

```sh
.sst/platform/src/components/aws/astro.ts:387:13 - error TS2416: Property 'buildPlan' in type 'Astro' is not assignable to the same property in base type 'SsrSite'.
  Type '(outputPath: Output<string>) => Output<{ base: any; server: { handler: string; nodejs: { install: string[]; }; streaming: boolean; copyFiles: { from: string; to: string; }[]; } | undefined; assets: { ...; }[]; custom404: string | undefined; }>' is not assignable to type '(outputPath: Output<string>, name: string, args: SsrSiteArgs, { bucket }: { bucket: Bucket; }) => Output<Plan>'.
    Type 'Output<{ base: any; server: { handler: string; nodejs: { install: string[]; }; streaming: boolean; copyFiles: { from: string; to: string; }[]; } | undefined; assets: { from: string; to: string; cached: boolean; versionedSubDir: string; }[]; custom404: string | undefined; }>' is not assignable to type 'Output<Plan>'.
      Property 'assets' is missing in type 'Output<{ base: any; server: { handler: string; nodejs: { install: string[]; }; streaming: boolean; copyFiles: { from: string; to: string; }[]; } | undefined; assets: { from: string; to: string; cached: boolean; versionedSubDir: string; }[]; custom404: string | undefined; }>' but required in type 'LiftedObject<Plan, NonFunctionPropertyNames<Plan>>'.

387   protected buildPlan(outputPath: Output<string>) {
                ~~~~~~~~~

  .sst/platform/src/components/aws/ssr-site.ts:88:3
    88   assets: {
         ~~~~~~
    'assets' is declared here.


Found 1 error in .sst/platform/src/components/aws/astro.ts:387
```

I get this in `3.10.1` - `3.10.4`, but not in `3.9.39`

**Comment by fwang** [comment]
@kasleet thanks for digging into it. Removed the `astro-sst` dependency in v3.10.5.
